# Generated by Django 6.0.1 on 2026-03-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('P', 'Personal'), ('W', 'Work'), ('S', 'Study'), ('F', 'Finance'), ('H', 'HouseHold'), ('O', 'Others')], default='Select', max_length=1),
        ),
    ]
